@baseUrl = http://localhost:3001

### Read all products
GET {{baseUrl}}/products

### Read products by id
GET {{baseUrl}}/products/1

### Add a product
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 49.99,
  "quantity": 1
}

### Update product by id
PUT {{baseUrl}}/products/2
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 49.99,
  "quantity": 1
}

### Delete product by id
DELETE {{baseUrl}}/products/3